services:
  frontend:
    container_name: Frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    network:
      - app-network
    ports:
    - "4001:80"
  
  backend:
    container_name: Backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    network:
      - app-network
    ports:
      - "4002:3000"

  database:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mi_db
    network:
      - app-network
    ports:
      - "4003:3306"

networks:
  app-networks:
    driver: bridge